name: asigment_demo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  connectivity_plus: ^2.3.6
  cached_network_image: ^3.2.1
  dio: ^4.0.6
  get_it: ^7.2.0
  get: 4.6.5
  flutter_staggered_animations: ^1.0.0
  flutter_animated_dialog: ^2.0.1
  local_auth: ^2.1.2
  path_provider: ^2.0.11
  sqflite: ^2.2.0+3
  vs_scrollbar: ^0.2.1
  get_storage: ^2.0.3
  http:
  shimmer: 2.0.0
  pull_to_refresh:
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

